# 配置数据池
spring:
  application:
    name: tlias-web-management

  #  配置数据库链接信息
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/tlias
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  servlet:
    multipart:
      #最大请求大小（包括所有文件和表单数据）
      max-request-size: 100MB
      #最大单个文件大小
      max-file-size: 10MB

# mybatis的配置
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #开启驼峰映射
    map-underscore-to-camel-case: true

#配置事务管理日志级别 --  debug
logging:
  level:
    org.springframework.jdbc.support.JdbcTransactionManager: debug

